openapi: 3.0.0
info:
  title: Student Course Management API
  description: API for managing student groups and students in a course system.
  version: 1.0.0

servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/HEITIAVINA3/StudentCourseManagementAPI/1.0.0

paths:
  /groups:
    get:
      summary: Retrieve a list of groups
      description: Get all groups, with optional filters by group name and year range.
      parameters:
        - name: groupName
          in: query
          description: Filter groups by name
          required: false
          schema:
            type: string
        - name: startYear
          in: query
          description: Filter groups created after this year (inclusive)
          required: false
          schema:
            type: string
            format: date
        - name: endYear
          in: query
          description: Filter groups created before this year (inclusive)
          required: false
          schema:
            type: string
            format: date
      responses:
        '200':
          description: A list of groups
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Group'
    post:
      summary: Add a new group
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Group'
      responses:
        '201':
          description: Group successfully created
    put:
      summary: Update an existing group
      description: Idempotent operation to update a group.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Group'
      responses:
        '200':
          description: Group successfully updated
    delete:
      summary: Delete a group
      parameters:
        - name: id
          in: query
          description: ID of the group to delete
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Group successfully deleted

  /students:
    get:
      summary: Retrieve a list of students
      description: Get all students, with optional filters by student name.
      parameters:
        - name: studentName
          in: query
          description: Filter students by name
          required: false
          schema:
            type: string
      responses:
        '200':
          description: A list of students
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Student'
    post:
      summary: Add a new student
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
      responses:
        '201':
          description: Student successfully created
    put:
      summary: Update an existing student
      description: Idempotent operation to update a student.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
      responses:
        '200':
          description: Student successfully updated
    delete:
      summary: Delete a student
      parameters:
        - name: id
          in: query
          description: ID of the student to delete
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Student successfully deleted

components:
  schemas:
    Group:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the group
        groupName:
          type: string
        groupYear:
          type: string
          format: date
          description: Year the group was created
        promotion:
          type: string
          enum:
            - G
            - H
            - J
            - K
        studentNb:
          type: integer
          description: Number of students in the group
        students:
          type: array
          items:
            $ref: '#/components/schemas/Student'

    Student:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the student
        name:
          type: string
        sex:
          type: string
          enum:
            - M
            - F
        birthdate:
          type: string
          format: date
        reference:
          type: string
          description: Unique student reference (e.g., STD23XXX)
        group:
          type: string
          description: Name of the group the student belongs to
